kube-prometheus-stack:
  crds: false   # попробуем отключить
  prometheus:
    prometheusSpec:
      retention: 24h
  grafana:
    enabled: true
    adminPassword: admin
  alertmanager:
    enabled: false
